config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :tracks
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated :user do
    root :to => 'tracks#index', as: :authenticated_root
  end
  
  root to: "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tracks

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @tracks = @user.tracks.order(created_at: :desc)
  end

  def show
    @user = current_user
    @track = Track.find(params[:id])
  end

  def new
    @user = current_user
    @track = Track.new
  end

  def create
    user = current_user
    track = user.tracks.new(track_params)

    if track.save
      flash[:notice] = 'The track was saved successfully.'
      redirect_to root_url
    else
      flash[:error] = 'Track not created'
      render 'new'
    end
  end

  private

  def track_params
    params.require(:track).permit(:name, :time, :distance, :coords, { speed: [] })
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RunningClub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>
  </head>

  <body>
    <% if notice.present? %>
      <p class="notice fixed z-10 bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 mt-4 ml-24 shadow-md text-sm"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert fixed z-10 bg-red-400"><%= alert %></p>
    <% end %>
    <div class="ml-12">
      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, :method => :delete%>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/tracks/index.html.erb
<header>
  <h1 class="mt-10 underline pt-5 text-2xl text-red-600">YOU ARE LOGGED IN</h1>
  <%= link_to 'START NEW RUN', new_user_track_path(@user.id) %>
  <ul>
    <% @tracks.each do |track| %>
      <%= link_to user_track_path(user_id: @user.id, id: track.id) do %>
        <li>
          <p><%= track.created_at %></p>
          <p><%= track.created_at.strftime("%d %b %Y") %></p>
        </li>
      <% end %>
    <% end %>
  </ul>
</header>

app/views/tracks/new.html.erb
<%= link_to root_url do %>
  <p>BACK</p>
<% end %>
<div>
  <p>WATCH:</p>
  <p id="stopwatch">00:00:00</p>
  <p>DISTANCE:</p>
  <p id="distance-box">0m</p>
</div>
<button id="start" onclick="getLocationUpdate()">Start</button>
<button id="stop" style="display: none;" onclick="stopWatch()">Stop</button>

<%= form_with model: @track, url: user_tracks_path(@user.id), method: :post do |f| %>
  <%= f.hidden_field :name, id:'name' %>
  <%= f.hidden_field :time, id:'time' %>
  <%= f.hidden_field :coords, id:'coords' %>
  <%= f.hidden_field :distance, id:'distance' %>

  <div id='speed-div' style="display: none;"></div>
  
  <%= f.submit "Save", id: 'save', style: 'display: none;' %>
<% end %>

<script>
  var watchID;
  var geoLoc;
  const startBtn = document.getElementById('start');
  const stopBtn = document.getElementById('stop');
  const saveBtn = document.getElementById('save');

  const timer = document.getElementById('stopwatch');
  var hr = 0;
  var min = 0;  
  var sec = 0;  
  var stoptime = true;  

  var speed = [];

  const dbox = document.getElementById('distance-box');
  var dist = 0;
  var lat1 = 0;
  var long1 = 0;

  var coords = [];

  const date = new Date();
  const dateDay = date.getDay();
  const dateHour = date.getHours();
  var day = '';
  var hour = '';

  switch(dateDay) {
    case 1:
     day = 'Monday ';
     break
    case 2:
     day = 'Tuesday ';
     break
    case 3:
     day = 'Wednesday ';
     break
    case 4:
     day = 'Thrusday ';
     break
    case 5:
     day = 'Friday ';
     break
    case 6:
     day = 'Saturday ';
     break
    case 7:
     day = 'Sunday ';
  }

  if(dateHour >= 5 && dateHour <= 11) {
    hour = 'Morning ';
  }

  if(dateHour >= 12 && dateHour <=16) {
    hour = 'Afternoon ';
  }

  if(dateHour >= 17 && dateHour <= 20) {
    hour = 'Evening ';
  }

  if(dateHour >= 21 || dateHour <= 4) {
    hour = 'Night ';
  }

  function getLocationUpdate() {
    if(navigator.geolocation){
      geoLoc = navigator.geolocation;
      toggle();
      watchID = geoLoc.watchPosition(data => {
        if (stoptime == true) {
          stoptime = false;
          timerCycle();
        }
        console.log(data);
        coords.push([data.coords.longitude, data.coords.latitude]);
        if(data.coords.speed) {
          speed.push(data.coords.speed);
        }
        if((lat1 !== 0) && (long1 !== 0)) {
          distance(lat1, data.coords.latitude, long1, data.coords.longitude)
        }
        lat1 = data.coords.latitude;
        long1 = data.coords.longitude;
      }, (error) => console.log(error),
      {
        enableHighAccuracy: true,
      });
    } else {
        alert("Sorry, browser does not support geolocation!");
    }
  }

  function stopWatch() {
    if (stoptime == false) {
      stoptime = true;
    }
    geoLoc.clearWatch(watchID);
    toggle();
    const len = speed.length;
    if(speed.length > 0) {
      for(var i = 0; i < len; i++) {
        var spd = document.getElementById('speed-div').appendChild(
            document.createElement('input')
        )
        spd.value = speed[i];
        spd.id = 'track_speed';
        spd.name = 'track[speed][]';
        spd.type = 'hidden';
        spd.step = 'any';
      }
    }
    document.getElementById('time').value = (sec * 1) + (min * 60) + (hr * 3600);
    console.log(coords);
    console.log(JSON.stringify(coords));
    document.getElementById('distance').value = dist;
    document.getElementById('coords').value = JSON.stringify(coords);
    document.getElementById('name').value = day + hour + 'Run';
  }

  function timerCycle() {
    if (stoptime == false) {
      sec = parseInt(sec);
      min = parseInt(min);
      hr = parseInt(hr);

      sec = sec + 1;

      if (sec == 60) {
        min = min + 1;
        sec = 0;
      }
      if (min == 60) {
        hr = hr + 1;
        min = 0;
        sec = 0;
      }

      if (sec < 10 || sec == 0) {
        sec = '0' + sec;
      }
      if (min < 10 || min == 0) {
        min = '0' + min;
      }
      if (hr < 10 || hr == 0) {
        hr = '0' + hr;
      }

      timer.innerHTML = hr + ':' + min + ':' + sec;

      setTimeout("timerCycle()", 1000);
    }
  }
 
  function distance(lat1, lat2, long1, long2) {
    if((lat1 == lat2) && (long1 == long2)) {
      dist += 0;
    } else {
      const R = 6371e3;
      var φ1 = lat1 * Math.PI/180;
      var φ2 = lat2 * Math.PI/180;
      var Δφ = (lat2 - lat1) * Math.PI/180;
      var Δλ = (long2 - long1) * Math.PI/180;
      var a = Math.sin(Δφ/2) * Math.sin(Δφ/2) +
        Math.cos(φ1) * Math.cos(φ2) *
        Math.sin(Δλ/2) * Math.sin(Δλ/2);
      var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));

      var d = R * c;
      dist += d;
    }
    dbox.innerHTML = Math.floor(dist) + 'm';
  }

  function toggle() {
    if (start.style.display === 'none') {
      startBtn.style.display = 'block';
      stopBtn.style.display = 'none';
      saveBtn.style.display = 'block';
    } else {
      startBtn.style.display = 'none';
      stopBtn.style.display = 'block';
      saveBtn.style.display = 'none';
    }
  }
</script>

app/views/tracks/show.html.erb
<%= link_to root_url do %>
  <p>BACK</p>
<% end %>
<h1>This track exists</h1>
<p>TIME SPENT:<%= @track.time %></p>
<p>CREATED AT:<%= @track.created_at%></p>
<p>NAME:<%= @track.name%></p>

<div style="display: flex; flex-wrap: wrap;">
  <div>
      <%= content_tag "div", id: "coords", data: {coords: @track.coords} do %>
      <% end %>
  </div>
  <div style="border-right: 1px solid;">
    <p>SPEED:</p>
    <div>
      <% @track.speed.each do |spd| %>
        <p><%= spd %></p>
      <% end %>
    </div>
  </div>
</div>

<div id='map' style='width: 400px; height: 300px;'></div>
<script>

  var coords = JSON.parse(document.getElementById('coords').dataset.coords);
  console.log(coords);

  mapboxgl.accessToken = 'pk.eyJ1IjoibGVvbmRpYXNiIiwiYSI6ImNsMHJiNGJyeDAxcnQzZG9wNDZwajNuNDYifQ.47GK1AdHnqacQY-pPpxK_Q';
  var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v11',
    center: coords[Math.floor(coords.length/2)],
    zoom: 15
  });
  
  map.on('load', () => {
    map.addSource('route', {
      'type': 'geojson',
      'data': {
        'type': 'Feature',
        'properties': {},
        'geometry': {
          'type': 'LineString',
          'coordinates': coords
        }
      }
    });
    map.addLayer({
      'id': 'route',
      'type': 'line',
      'source': 'route',
      'layout': {
        'line-join': 'round',
        'line-cap': 'round'
      },
      'paint': {
        'line-color': '#888',
        'line-width': 8
      }
    });
  });
</script>

app/views/users/index.html.erb
<% if current_user %>
  <%= link_to 'tracks', user_tracks_path(@user.id) %>
<% else %>
  <div class="flex flex-col items-center justify-between bg-zinc-100 absolute w-full h-full">
    <div class="relative top-1/3">
      <h1 class="text-red-500 text-5xl font-bold">RunningClub</h1>
    </div>
    <div class="w-full flex items-center">
      <%= link_to 'LOG IN', new_user_session_path, class: 'block text-center text-white bg-gray-800 p-4 duration-300 hover:bg-black active:bg-black focus:bg-black w-full', style: '' %>
      <%= link_to 'SIGN UP', new_user_registration_path, class: 'block text-center bg-white p-4 duration-300 rounded-sm hover:bg-zinc-200 active:bg-zinc-200 focus:bg-zinc-200 w-full', style: '' %>
    </div>
  </div>
<% end %>